spring.application.name=TallerJPA

server.port=${SERVER_PORT:8080}

spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:tallerjpa}
spring.datasource.username=${POSTGRES_USER:tallerjpa}
spring.datasource.password=${POSTGRES_PASSWORD:tallerjpa}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.defer-datasource-initialization=true
spring.jpa.open-in-view=false
spring.sql.init.mode=never

jwt.secret=${JWT_SECRET:miClaveJWTUltraSeguraParaHS512ConLongitudSuperiorASesentaYCuatroCaracteresYCompatibleConSpringBoot2026}
jwt.expiration=${JWT_EXPIRATION:86400000}
